sudo: required
language: android
android:
  components:
  - tools
  - build-tools-26.0.1
  - android-19
  - android-21
  - android-22
  - android-23
  - android-24
  - android-26
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-19
  - sys-img-armeabi-v7a-android-21
  - sys-img-armeabi-v7a-android-22
  - sys-img-armeabi-v7a-android-24

jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
env:
  matrix:
  - API=android-19 ABI=armeabi-v7a
  - API=android-21 ABI=armeabi-v7a
  - API=android-22 ABI=armeabi-v7a
  - API=android-24 ABI=armeabi-v7a
  global:
  - ADB_INSTALL_TIMEOUT=8

install: true

script:
- ./gradlew build jacocoTestReport
- echo no | android create avd --force -n test -t $API --abi $ABI
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
- provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - $TRAVIS_BUILD_DIR/library/build/outputs/aar/library-debug.aar
    - $TRAVIS_BUILD_DIR/library/build/outputs/aar/library-release.aar
  skip_cleanup: true
  on:
    tags: true
    repo: watson-developer-cloud/android-sdk
    condition: "$API = android-19"
- provider: bintray
  file: $TRAVIS_BUILD_DIR/descriptor.json
  user: lpatino10
  key: 
    secure: "GgkyRI9L+OeaM77vpkrno3j1u7EsMKLXoSZL+1YxgUChADWrEUkksldCApit7JnIzatihce/8B/J+T7ySOE4hO4l7o7qdoy/yNbwuEx3ROCwq8G/nsYGvIp50xSiDPkwEF3xidRh0iee2kOq3pWOP1RiRIGPZ6g3lQ5W90JTh1LQ7D9PAxRmqmmCnv+9Z48cMjFQCSFP6ymm3oxGh6yIY9uosnlle1hm/obQyysDS7iRTws/mNx4fZcnAfUBHE0epcpASP60wOZzmBbq2tvSdD5M5eMK6c9PBhinJ397YOI4MeTVzGqW0qXQLKVnyh4CwoVVqsNTdIG8VSs6ObL32zDoQaJgbhjVQI0wgFer7BK4x9t+VgXc6A2L+cjeDRDJKBVDrf0wPUIeQmZ87Dhu7P/QwEwRAK2YrlxP3atlEFgoV2Dy/MVbFl1JDQf8idJw4/+bqxyCcf3G7J4e7qWiU/qXhlx7Fx6kMFd2I/r4HlDsNmG1m/TzKSJY6kuBmLIzTUW8iu9TL3WhuFIuR2R3eyLNYwmR8s/YJL/WOy/xqhUUg/886rI+rirxcxKrRh0U4uKT5fsxnqLT5DR6ZspcUnfRLAoh2BlKtbue2T+FWuO2DoHehk6pZdZYmoBYtJsFBmKOXoj2U3jcRSMQkPNqumzTV2TS2xHAFkGSrpe+GMQ="
  skip_cleanup: true
  on:
    tags: true
    repo: watson-developer-cloud/android-sdk
